// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjTAcGZkR-IoLXUVFoDdaN4V-tglGBsPY',
    appId: '1:682597654270:web:7ad884a2c8bf746be2cfaf',
    messagingSenderId: '682597654270',
    projectId: 'sportapp-4b124',
    authDomain: 'sportapp-4b124.firebaseapp.com',
    storageBucket: 'sportapp-4b124.appspot.com',
    measurementId: 'G-EV1N15CB0S',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAAy35rSfFgTtJnTYQyfUq5bqa78XO1Trc',
    appId: '1:682597654270:android:215b6c3666a8e45ce2cfaf',
    messagingSenderId: '682597654270',
    projectId: 'sportapp-4b124',
    storageBucket: 'sportapp-4b124.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqHwbWwMw5wnXV3tMIoyckAf-EFfZ-gw',
    appId: '1:682597654270:ios:b8ca423fc8c206d1e2cfaf',
    messagingSenderId: '682597654270',
    projectId: 'sportapp-4b124',
    storageBucket: 'sportapp-4b124.appspot.com',
    iosBundleId: 'com.example.sportapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIqHwbWwMw5wnXV3tMIoyckAf-EFfZ-gw',
    appId: '1:682597654270:ios:b8ca423fc8c206d1e2cfaf',
    messagingSenderId: '682597654270',
    projectId: 'sportapp-4b124',
    storageBucket: 'sportapp-4b124.appspot.com',
    iosBundleId: 'com.example.sportapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBjTAcGZkR-IoLXUVFoDdaN4V-tglGBsPY',
    appId: '1:682597654270:web:5940baae1b7a654fe2cfaf',
    messagingSenderId: '682597654270',
    projectId: 'sportapp-4b124',
    authDomain: 'sportapp-4b124.firebaseapp.com',
    storageBucket: 'sportapp-4b124.appspot.com',
    measurementId: 'G-Q0N9G6C15M',
  );
}
